package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@javax.persistence.Table(name = "DO1")
public class DO1 implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("id")
	private java.lang.Integer id;
	@org.kie.api.definition.type.Label("name")
	@javax.persistence.Column(name = "DO1")
	private java.lang.String name;

	@javax.persistence.GeneratedValue(generator = "DO1_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "DO1_ID_SEQ", name = "DO1_ID_GENERATOR")
	private java.lang.Long id1;

	public DO1() {
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Long getId1() {
		return this.id1;
	}

	public void setId1(java.lang.Long id1) {
		this.id1 = id1;
	}

	public DO1(java.lang.Integer id, java.lang.String name, java.lang.Long id1) {
		this.id = id;
		this.name = name;
		this.id1 = id1;
	}

}